services:
  - type: web
    name: documend-backend
    env: python
    region: oregon
    buildCommand: "chmod +x ./render-build.sh && ./render-build.sh"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
